"""Initial migration

Revision ID: c2ff8a31efca
Revises: 
Create Date: 2024-08-26 09:44:50.619944

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c2ff8a31efca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('student',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('surname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('initials',
               existing_type=mysql.VARCHAR(length=8),
               nullable=False)
        batch_op.alter_column('degree',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('campus',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('vaal', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=False,
               autoincrement=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaal', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=mysql.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
        batch_op.alter_column('campus',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('degree',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('initials',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)
        batch_op.alter_column('surname',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('title',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('student',
               existing_type=mysql.VARCHAR(length=8),
               nullable=True)

    # ### end Alembic commands ###
